### ISSUE TITLE
being able to idle different games per account

### ISSUE THREAD

**Issue by tailon222** [3urobeat/steam-idler#11]
Hi i would like to request a future if is possible, would it be possible to add idle list per account, so i can for example idle in account 1, cs:go and in account 2 another game that is not free to play and i dont have in all accs? 
I have seen other scripts in the past with the same accounts.txt file format in they used it this way: 
AccoutName:AccountPassword:gameids

Thanks!

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue!  
Sure, that would be possible, although I wouldn't put it behind the login credentials as that is reserved for shared_secrets.  
I guess I'd need to make the `playingGames` setting in the config an object where you can specify an accountName and then the games that account should play.  
For now you should be able to specify all games though. I think accounts that don't have that game will just not display it (although I haven't tested if `requestFreeLicense()` throws an error for non-free games).

**Comment by tailon222** [comment]
yeah i can specify the games but the thing is that if i want to idle max games per account (32) all the time, then i won't be able to do it because if i put an appid of a game that is not free to play then in the other accounts it will only idle 31 games, and that goes on if i put more appids from a non free to play games. Also if for example i only want to idle dota 2 in one account and csgo in other account but both accounts have both games it will idle both not just dota 2 or csgo.
I probably explained myself a bit bad, sorry for that.

This is just to get extra fanciness to the app, take as much time as you need. Thanks :)

**Comment by 3urobeat** [comment]
Hey! I have just released version 1.7 which adds support for this feature.  
I have tested this feature only briefly, so please let me know if you encounter any issues or if the documentation is unclear.  

I'll leave this issue open for a few more days/weeks.  
If everything is clear you can also close this issue if you wish. Thanks again for the idea!  
Have a nice day :)

**Comment by tailon222** [comment]
Thank you so much for the update! i have been testing it and works perfectly. Now i can have all my accs in 1 instance.
I read the documentation and i was a bit confused at first but that's probably because my bad English level.

In the example shows the games configuration with the "In non-Steam game" display, for some people is not worth it to put that because it takes 1 slot for an actual game and i think there's not example without that.  

So i have it this way: (maybe you could add it to the documentation too if you want)
` "playingGames": [{ "myacc1": [730,570], "myacc2": [570] }, 440],`

myacc1 = plays CS:GO and Dota
myacc2 =  plays Dota
rest of accounts play TF2 

Also something to remember is that we should end the line with `","` otherwise script will crash with a Syntax Error. 
Thank you so much for you hard work! Have a good day! :)

**Comment by 3urobeat** [comment]
Thanks for the feedback, I'll improve the documentation!  
I'm going to close this issue; should you encounter any issues with this feature later on please feel free to reopen it!

**Comment by 3urobeat** [comment]
Whoops, looks like I did make a mistake - requesting a missing license throws a syntax error.  
I've already fixed it and will release version 1.8 today, just wanted to let you know :)

**Comment by tailon222** [comment]
Thank you!! i already had all the games on the accounts so maybe that's why i did not get that error, glad you got it fixed.  :)
