### ISSUE TITLE
QR code login

### ISSUE THREAD

**Issue by vstrg** [3urobeat/steam-idler#13]
Hey, can you add login with qr code?

**Comment by 3urobeat** [comment]
Hey, thanks for the suggestion.  
I yet have to implement this feature into my steam-comment-service-bot, not completely sure how to yet.  
When that is working I'm going to port it over to this project.  
Related issue: https://github.com/3urobeat/steam-comment-service-bot/issues/193

**Comment by 3urobeat** [comment]
Version 1.9 is now out which includes this feature. Please let me know if you run into any issues!  
Read the full changelog [here](https://github.com/3urobeat/steam-idler/releases/tag/1.9)
