### ISSUE TITLE
How much hours played with bot

### ISSUE THREAD

**Issue by vstrg** [3urobeat/steam-idler#14]
Hey, if the timer starts when the bot starts playing with the bot and stops when it is turned off, then exports it to a file so that it can be calculated how many hours it has been played. This method that comes to my mind can be calculated in a different way, I would be pleased if you add this feature. Thanks.

**Comment by 3urobeat** [comment]
Hey, sure, this could be implemented fairly easily. I'll look into it.

**Comment by 3urobeat** [comment]
Version 1.9 is now out which includes this feature.  
The bot creates a new `playtime.txt` file and logs information about the last session for every account on every relog/stop. This feature is enabled by default but can be turned off in the config.  
Read the full changelog [here](https://github.com/3urobeat/steam-idler/releases/tag/1.9)
