### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by Jakub-Kogut** [3urobeat/steam-idler#15]
Hello how to add token from mobile phone? The tokens.db should be clear without any code? Or should I add something by myself?

**Comment by Jakub-Kogut** [comment]
[ERROR] [username] Couldn't log in. Error: InvalidPassword (5)
Note: The error "InvalidPassword" (5) can also be caused by a wrong Username or shared_secret!
      Try leaving the shared_secret field empty and check username & password.
[2023-09-27 15:24:06 | ERROR] [username] Couldn't log in! Continuing with next account...
[2023-09-27 15:24:06 | INFO] Logging in password in 2 seconds...
[2023-09-27 15:24:06 | INFO] [password] No token found in tokens.db. Logging in with credentials to get a new session...

Getting this in terminal after running

**Comment by 3urobeat** [comment]
Hey, thanks for opening an issue.  
The tokens database must not be touched, yes. The bot will populate it with a so called refreshToken when obtaining a session.  

What do you mean with mobile phone token?  
A shared_secret? Is explained in the README.  
The steam guard code? Start the bot, let it log in and it will ask you for it.

I'm not sure what I am looking at in your log excerpt. Did you not provide any accounts? Or did you censor [username]?  
You need to provide the correct login credentials for your Steam accounts you want to idle games on in the accounts.txt file (as explained in the README).

**Comment by 3urobeat** [comment]
Great to hear!  
If you've got anything else feel free to open another issue! :)
