### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by vstrg** [3urobeat/steam-idler#22]
Hey, when someone with Chinese alphabet or non-Latin alphabet nick sends a message, it gives such an error and the bot stops

![Screenshot_1](https://github.com/user-attachments/assets/2f6cae82-9d02-47ae-97c4-f9880c886325)

**Comment by 3urobeat** [comment]
Huh, well that's interesting. Thanks for reporting!  
I'll check it out further and will let you know when I know more.

**Comment by 3urobeat** [comment]
This wasn't necessarily caused by a non-latin nickname but rather from a new user not being cached yet.  
I've put a check around it so that it won't crash the bot anymore.

I'll leave this issue open until v1.10 is finished.

**Comment by 3urobeat** [comment]
Version 1.10 is now out and can be downloaded from the repository.
