### ISSUE TITLE
Goodbye! issue

### ISSUE THREAD

**Issue by vstrg** [3urobeat/steam-idler#23]
Hey, when the connection is lost, it tries to reconnect, but rarely after logging, it says goodbye and the bot exit
![Screenshot_2](https://github.com/user-attachments/assets/3a9baec2-a9bb-4619-ab18-46b33ae1ff6e)

**Comment by vstrg** [comment]
problem caused by the old vds provider I used, I tried with the new vds provider and had no problem

**Comment by 3urobeat** [comment]
Oh. interesting, thanks for the update.  
Sorry that I did not respond to your original message, I was wondering how one would even start to debug this issue. I am planning to start working on another update for this project soon, I would have responded then.

Maybe your old vds provider killed the process after some time, really not sure what else might cause this. The bot can't really stop out of the blue without any message whatsoever.
