### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by ultninjaF** [3urobeat/steam-idler#29]
Crashes after 20 minutes of working, everytime same problem.
![WindowsTerminal_rn7v6oMXOU](https://github.com/user-attachments/assets/6a693a6b-7777-4c7c-b2c5-dd8be1945583)

**Comment by 3urobeat** [comment]
Hey, this was already fixed 3 weeks ago in commit [5ef1cee](https://github.com/3urobeat/steam-idler/commit/5ef1ceefce9de5171ab195192eeede40e3f8156e).  
Please re-download the bot. Thanks!

**Comment by ultninjaF** [comment]
I've downloaded it today)

**Comment by ultninjaF** [comment]
So I redownloaded bot.js. It works now. But when I downloaded from 1.10 version (latest release) there were file with error)

**Comment by 3urobeat** [comment]
Yeah, I didn't create a new Release for that one extra commit. Sorry for the confusion.
